[package]
name = "treeify"
version = "0.1.0"
authors = ["Loïc Damien <loic.damien@dzamlo.ch>"]
repository = "https://github.com/dzamlo/treeify"
license = "MIT OR Apache-2.0"

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
